### ISSUE TITLE
软件板块横向滚动需设最大最小值

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#20]
滚到头那个图应该 fix 在最右边，不再向左移动了，往回滚时同理。
https://user-images.githubusercontent.com/869101/168308496-ca851509-0804-44be-ab3b-7effa85fbc77.mp4

**Comment by limichange** [comment]
@imneway 我试了一下，如果两边顶着的话，整个画面进来出去要有一小段的停顿，不然头尾两个一下子就划走了。

**Comment by imneway** [comment]
ok，可以加点试下效果。
我刚又找了些类似效果的网站，第一个是到头就划走，可能它版面很大，看着还行，第二个是在最后一张图后面再加了点东西，以致于滑走时不至于太空，你看如果太 tricky 的话我就参考第二种，在最后再加点内容：
https://www.juni.co/
https://h-u-g.co.jp/

**Comment by limichange** [comment]
https://fix-scroll-limit--onekey-website.netlify.app/

**Comment by imneway** [comment]
把起点和终点和 column 两端对齐好实现吗？如下图示意。目前小窗口还好，大屏上是不太理想。

<img width="2491" alt="image" src="https://user-images.githubusercontent.com/869101/170682291-6b7fa31a-8a58-475d-8569-72be34165acb.png">

<img width="2468" alt="image" src="https://user-images.githubusercontent.com/869101/170682312-95797269-4b4b-421a-9654-4c599b65da64.png">

**Comment by limichange** [comment]
懂了

**Comment by limichange** [comment]
https://fix-scroll-limit--onekey-website.netlify.app/

**Comment by imneway** [comment]
赞！开头的停顿可以去掉了，保留结尾的就行

**Comment by limichange** [comment]
https://fix-scroll-limit--onekey-website.netlify.app/
