### ISSUE TITLE
Backed by the Best 小问题

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#23]
1. 滚动方向反过来好些
2. Backed by the Best 这几个字是灰色的
3. 设计稿 logo 有缺失，刚补齐了： https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=5232%3A18157

**Comment by imneway** [comment]
还是反了哈，logo 摆放顺序和滚动方向如下图
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/869101/169447274-a9ede143-dea1-4e87-8b44-927a4dd4cf09.png">

**Comment by imneway** [comment]
@limichange 这个好像漏了，参考上一条评论

**Comment by imneway** [comment]
@limichange 我看这个链接里 Logo 顺序和滚动方向还是不对？

logo 顺序是按上图的，dragonfly capital 排第一位，ribbit capital 第二……现在还是倒过来的。

https://feature-update-rewards-images--onekey-website.netlify.app/

**Comment by limichange** [comment]
不知道为啥 这个链接炸了 看下面这个
https://fix-rewards-section--onekey-website.netlify.app/

**Comment by imneway** [comment]
赞，好了
