### ISSUE TITLE
硬件版块 hover 效果

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#25]
后期可以加上
<img width="561" alt="image" src="https://user-images.githubusercontent.com/869101/168312876-c66b6928-c8b7-477c-a759-ac9719c649e2.png">

**Comment by imneway** [comment]
@limichange 这个鼠标指针可以先弄着，也是加分项

**Comment by imneway** [comment]
挺接近了，补充一些小细节，有些是根据实现效果重新调整的：
1. 鼠标移走时的淡出效果可以再干脆利落些，现在有比较明显的 scale down 拖影。可参考 Custo 的（在大概第三屏的地方）： https://custo.io/
2. 绿色指针有点偏大，我缩小了些。
3. 我调整了下设计稿，让 hover 和非 hover 对比更明显。

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4479%3A12918

![CleanShot 2022-07-14 at 20 53 57@2x](https://user-images.githubusercontent.com/869101/178988601-603bc08e-602d-42ad-a99f-7d3fb312af12.png)


![CleanShot 2022-07-14 at 20 55 13@2x](https://user-images.githubusercontent.com/869101/178988586-776beba0-6c49-4d86-95b0-fe9cd2116088.png)

**Comment by limichange** [comment]
https://onekey-portal-git-feature-green-point-limichange.vercel.app/

**Comment by imneway** [comment]
现在又太干脆了😅，还是得有点淡入淡出缓动效果……

**Comment by limichange** [comment]
https://onekey-portal-on8faus2q-limichange.vercel.app/

**Comment by limichange** [comment]
https://onekey-portal-gj1ycf53u-limichange.vercel.app/

**Comment by imneway** [comment]
挺好！我没问题了！
