### ISSUE TITLE
安全版块的图应该等比缩放

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#39]
如图，不同尺寸下，它的宽高比是一致的，不是只拉伸宽度，高度不变
<img width="738" alt="image" src="https://user-images.githubusercontent.com/869101/169563760-f52ca3bf-6517-43df-8044-642f9dd1e5e4.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/18

**Comment by imneway** [comment]
最大宽度下还有被裁的情况（可能我看的不是最新版）
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/869101/169968365-22ed6385-93c6-48c2-a9ed-d4c298cd4d79.png">

**Comment by limichange** [comment]
https://fix-security-section-style--onekey-website.netlify.app/

**Comment by imneway** [comment]
图片下面会少一截：
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/869101/170467056-3a3d5236-c209-4b26-a035-f03721c3b9e1.png">

**Comment by limichange** [comment]
https://fix-security-section-style--onekey-website.netlify.app/

**Comment by limichange** [comment]
https://user-images.githubusercontent.com/1947344/170910095-cf54c8c0-0be0-4c5b-b944-49bdd887669a.mp4

**Comment by imneway** [comment]
看漏，现在没问题了
