### ISSUE TITLE
安全版块的间距

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#41]
如图一，文字和图的间距有误，参考图二，文字其实只占 5 栏，和图之间空一栏出来：

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/869101/169564566-27332aaa-b00b-48e9-bbb9-e6734b5916ce.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/869101/169564759-cd4ed368-9214-4d6d-a2fa-3d39d7662cac.png">

**Comment by limichange** [comment]
https://fix-security-section-style--onekey-website.netlify.app/
