### ISSUE TITLE
Why choose onekey 的宽度

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#42]
如图二，它应该也是 12 栏宽，和其它版块一致，不是占满整个窗口宽度。
<img width="2464" alt="image" src="https://user-images.githubusercontent.com/869101/169565230-108b60d2-ef55-4097-9cea-0cbdb3fe8209.png">
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/869101/169565377-6da84fe6-a0a5-4b2b-af57-d06e0281985f.png">

**Comment by limichange** [comment]
https://feature-why-section-style--onekey-website.netlify.app/
