### ISSUE TITLE
Why choose onekey 翻页按钮状态

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#43]
还是有个 disable 状态好些（不是鼠标指针），disable 是正常按钮透明度变为 40%。

另外目前两个按钮里的箭头是灰色，不是黑色，也需要修正下。

<img width="286" alt="image" src="https://user-images.githubusercontent.com/869101/169565993-4f368638-bc9c-4cc9-8faa-dbafe70eb09c.png">

**Comment by limichange** [comment]
https://feature-why-section-style--onekey-website.netlify.app/

**Comment by imneway** [comment]
箭头颜色还是不对，麻烦修正下

**Comment by limichange** [comment]
我看是黑色加了透明度

**Comment by limichange** [comment]
知道什么意思了

**Comment by imneway** [comment]
嗯，有透明度是 disable 状态哈

**Comment by limichange** [comment]
Remove the default button opacity.

https://user-images.githubusercontent.com/1947344/170620854-9666213b-a025-4a6b-a62c-6cf295b0a77b.mp4


https://feature-why-section-style--onekey-website.netlify.app/
