### ISSUE TITLE
第二屏序列帧间距再加大

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#45]
由于滚动距离不够，序列帧播的还是太快了……麻烦再加 200px 试试：
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/869101/169567033-162b5975-b0a6-434e-95e7-08375fc06489.png">

**Comment by limichange** [comment]
要不改成触发播放模式

https://user-images.githubusercontent.com/1947344/169945395-f92111cc-4899-4e7e-a4a9-1279030792f4.mp4

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/23
