### ISSUE TITLE
导航下拉最好可以等比缩放

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#46]
<del>如图，窗口宽度过大或过小时，下拉就不和谐了，最好能按那种 vw 的方式，让高度也等比缩放。</del>
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/869101/169568137-663c41b1-2311-49e9-941b-16f458f2d73c.png">

**Comment by imneway** [comment]
这个先 on hold 下，我再改改

**Comment by imneway** [comment]
设计调整：
- 下拉菜单缩小了高度
- 补充了各断点的自适应参考

不同窗口下，只缩放宽度即可，高度不用变。但那个图的缩放逻辑不太对，如下图 1440 宽度缩得好小，麻烦优化下，让它和各断点设计稿一致。

设计稿在各尺寸画布最下面，如图二示意。

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/869101/169797627-4282206d-b5e0-4986-9b08-fd6a01adee1f.png">
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/869101/169798046-708b7c6a-62f4-4ba6-9243-911a55505f9e.png">

**Comment by limichange** [comment]
https://feature-product-panel--onekey-website.netlify.app/

**Comment by imneway** [comment]
自适应 Ok，很棒 👍
mini 的图我没刷出来，不知是不是网络问题。

**Comment by limichange** [comment]
https://62904b5cc2683f00098b63ab--onekey-website.netlify.app/
