### ISSUE TITLE
导航下拉的 get started 是有链接的

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#47]
这块点了是打开帮助中心：https://help.onekey.so/hc/en-us/categories/360000170236-User-s-Guide
可以补一下

<img width="840" alt="image" src="https://user-images.githubusercontent.com/869101/169568592-79b11a40-1e35-44b7-b808-402be4e25f84.png">

**Comment by imneway** [comment]
补了个 hover 样式，背景轻微变色：https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=5223%3A18183

**Comment by limichange** [comment]
https://feature-getting-started--onekey-website.netlify.app/
