### ISSUE TITLE
软件版块的序列帧能否从代码上来延长滚动距离？

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#49]
现在这块也是刷的就滚完了，不知从代码上能否延长滚动距离，让它滚多一两下鼠标才结束？
<img width="2001" alt="image" src="https://user-images.githubusercontent.com/869101/169640686-4666c2b9-b970-4f9b-983e-f9a74a3486ae.png">

**Comment by limichange** [comment]
https://home-frames-player--onekey-website.netlify.app/

**Comment by imneway** [comment]
@limichange 我更新了背景序列帧图，让它看起来“停留时间更长”，麻烦有空换上试试
https://www.dropbox.com/home/Projects/OneKey/C4D/renders/home-software-header

**Comment by limichange** [comment]
https://home-frames-player--onekey-website.netlify.app/
