### ISSUE TITLE
Ghost button hover 也是变黑色的

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#51]
如图，麻烦全局替换下：
<img width="487" alt="image" src="https://user-images.githubusercontent.com/869101/169640865-3c84646c-fdc0-4f58-96b3-e5df3d93b4f3.png">

**Comment by imneway** [comment]
如果 ghost button 是白色，hover 则也是变白色（比如 Footer 订阅按钮）

**Comment by limichange** [comment]
footer 那是 gray，你看链接里的能接受么

https://refactor-button-component--onekey-website.netlify.app/

**Comment by imneway** [comment]
最好是白色的。

是不是把 footer 按钮变成白色就好？

btw footer 这个按钮其实就是白色的哈，设计稿的灰色应该是 input 没填写，所以有个置灰状态。黄冀在这里设计了输入状态：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3720%3A16159

**Comment by limichange** [comment]
https://feature-email-style--onekey-website.netlify.app/
