### ISSUE TITLE
补充 footer 社交媒体按钮 hover 样式

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#52]
如图，这三个图标 Hover 变绿有点怪，改成 Hover 透明度变为 80%：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4479%3A12918

<img width="638" alt="image" src="https://user-images.githubusercontent.com/869101/169641034-1091d427-c9f4-4d12-a9e3-2be4314817c2.png">

**Comment by limichange** [comment]
https://feature-footer-media-icon-hover-style--onekey-website.netlify.app/
