### ISSUE TITLE
移动端下硬件版块的图没居中

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#54]
如图，Onekey mini 偏右了：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/869101/169641496-17b5fbf2-4b13-49f5-a3b7-2cb6ffa36f0a.png">

**Comment by imneway** [comment]
btw 这里应该显示 onekey mini 的渲染图，不是线框图（因为没法 hover )

**Comment by limichange** [comment]
https://fix-hardwave-image-mobile-position--onekey-website.netlify.app/

**Comment by limichange** [comment]
https://user-images.githubusercontent.com/1947344/170174103-84f62ed0-13c5-4a9f-b8c2-16e796217b55.mp4
