### ISSUE TITLE
移动端首屏调整

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#55]
1. 细节需要和设计稿对齐下，如文字换行位置，按钮摆放，mask 的高度等
2. 背景图比较糊，另外位置是偏上一点的（手机在视觉中央）（切图在这里： https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3944%3A16886）
3. 滚动后不需要缩小宽度

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4501%3A14360

<img width="470" alt="image" src="https://user-images.githubusercontent.com/869101/169641651-d0cc923e-74a8-4dae-ade1-2fc57ceb6950.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/869101/169641664-bd8f6e33-70c7-4fbf-b3f0-79f493fb4e64.png">

**Comment by imneway** [comment]
补充：刚把首屏两个按钮换成了大号的：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4501%3A14360

<img width="442" alt="image" src="https://user-images.githubusercontent.com/869101/169677797-a46f1405-5986-4669-8e6f-a43a7a68d81e.png">


（目前按钮根据设计稿大小分成 小 中 大三个尺寸）
<img width="349" alt="image" src="https://user-images.githubusercontent.com/869101/169677778-1a40482c-2779-4794-b16c-241a538ba655.png">

**Comment by limichange** [comment]
@imneway PC 和 Mobile 都是大号按钮？

**Comment by imneway** [comment]
PC 不用变，还是 medium

**Comment by limichange** [comment]
https://fix-mobile-hero-style--onekey-website.netlify.app/

**Comment by imneway** [comment]
样式没问题。
就是加载时会出现视频占位图，移动端去掉吧。

**Comment by limichange** [comment]
这个改了，忘记说了，现在正式里就能看到修改。

**Comment by imneway** [comment]
Cool 好了
