### ISSUE TITLE
标题统一加上句号

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#57]
之前疏忽了，标题有的有句号，有的没有，现统一加上了句号，可参考 1440 设计稿：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4059%3A18261

<img width="325" alt="image" src="https://user-images.githubusercontent.com/869101/169642110-2f9a4736-6620-4cd1-904d-a5354b1502d3.png">

**Comment by limichange** [comment]
https://update-text--onekey-website.netlify.app/
