### ISSUE TITLE
首屏背景加上视频

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#58]
首屏背景的视频版本做好了，设想是像 zoox 首屏动效一样，播放一次并停留在最后一帧即可。移动版仍用静态图即可，不需要动效。

视频位置（已压缩）：
https://www.dropbox.com/s/a021zrzka9j1w74/home-hero-animation%402x%28compressed%29.mp4?dl=0

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/869101/169687955-fbcc78cb-09b1-4f28-b110-5414985be160.png">

**Comment by imneway** [comment]
另外是否需要 poster image？

**Comment by disinfeqt** [comment]
需要 poster；实现那个效果只要关掉 loop 就可以了。

**Comment by imneway** [comment]
好的，刚发现 poster 有现成的，在这里：https://www.dropbox.com/preview/Projects/OneKey/C4D/renders/home-hero/home-hero-motion0000.jpg

**Comment by limichange** [comment]
移动版是用第一帧还是最后一帧？

**Comment by imneway** [comment]
可以用单独的图不？即之前这张：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3944%3A16886

**Comment by limichange** [comment]
https://hero-video--onekey-website.netlify.app/

**Comment by imneway** [comment]
@limichange 一开始会闪一下，是 Poster 还是什么问题？ https://share.cleanshot.com/o8T5UK

**Comment by limichange** [comment]
刚看到了，改完了，等一下更新

**Comment by limichange** [comment]
https://hero-video--onekey-website.netlify.app/

**Comment by imneway** [comment]
视频的闪烁没有了。
现在一开始会先加载出最后一帧（静态图），然后才从头开始播放，这个不好改对吧？

**Comment by limichange** [comment]
因为视频加载前，肯定要放一张图在那边

**Comment by limichange** [comment]
那个图是随便改的，不是从视频里加载出来的

**Comment by imneway** [comment]
了解，那张占位图用这张吧，即第一帧的图： https://www.dropbox.com/preview/Projects/OneKey/C4D/renders/home-hero/home-hero-motion0000.jpg

**Comment by imneway** [comment]
@limichange 请教下，
1. 如果在视频结束后，视频替换成（高质量的）静态图，实现会不会很 tricky？
2. 刚想起占位图尺寸不用那么大，可以缩小成 50% 的，这样加载是不是可以快些？

**Comment by limichange** [comment]
## 1
不会，可以播放完后 fade in

## 2
![CleanShot 2022-05-30 at 10 49 01@2x](https://user-images.githubusercontent.com/1947344/170908237-9ca85d86-41ea-4ac0-a590-d4bac78e804f.jpg)
感觉还好。

**Comment by imneway** [comment]
了解，那我在 Onekey 那个 Issue 里 https://github.com/OneKeyHQ/portal/issues/56 更新下首屏素材
2 原来这么小，那就忽略了

**Comment by limichange** [comment]
嗯，后面更新的时候，我再把图片质量降低一些，可能体积也就不到 10kb

**Comment by imneway** [comment]
cool 👍
