### ISSUE TITLE
导航栏 item 居左排列

### ISSUE THREAD

**Issue by imneway** [dinehq/portal#59]
如图：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4046%3A17107

<img width="750" alt="image" src="https://user-images.githubusercontent.com/869101/169798588-29aaf71e-8bc7-4cd3-90dd-5123c7f5502d.png">

**Comment by limichange** [comment]
https://feature-navigation-items-align--onekey-website.netlify.app/
